### PR TITLE
update VALID_FREQUENCIES_BY_FREQUENCY_TYPE to include 15 min

### PR DESCRIPTION
**Pull request by corncobb**
- Updated VALID_FREQUENCIES_BY_FREQUENCY_TYPE to include 15 min. 15 minutes is supported by the TDAmeritrade api but not by this library. You can see [here](https://developer.tdameritrade.com/price-history/apis/get/marketdata/%7Bsymbol%7D/pricehistory).
- Updated documentation to include 15 min.

**Note:** I tested the new 15 min implementation with C++ only.

Let me know if you need me to make adjustments before merging.

Thank you

### CODE REVIEW

**Comment by jeog** [comment]
Thanks for the contribution. Update looks good, but I notice there are 1000+ lines changed in the README from what looks like dropped spaces. Were there any substantive changes to the README or can I just ignore those?

- jon

**Comment by corncobb** [comment]
There were NOT any substantive changes. I only adjusted the block where VALID_FREQUENCIES_BY_FREQUENCY_TYPE was mentioned and Visual Studio Code formatted that file when I saved.

If you would like, I can revert back, make my changes, and save without formatting that file. Otherwise you can just ignore those dropped spaces.

Just let me know. I apologize for the inconvenience.

**Review by jeog — CHANGES_REQUESTED** [review]
Please update the README.md to avoid all the formatting changes and I'll confirm the request. (You should be able to just checkout the file from the previous commit, open the file in something like notepad that won't force any formatting, and make any changes concerning your code update.)

Not a big deal, I just want to keep the changes as minor as possible so its easy to isolate what was actually changed if we look back at some point in the future.

Thanks again.

**Comment by corncobb** [comment]
Should be fixed now. Check again. Let me know if there is anything else you want adjusted.

Thank you

**Pull request merged**
